server:
  port: 8053
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8050/eureka/

spring:
  flyway:
    baseline-on-migrate: true
  jpa:
    properties:
      javax:
        persistence:
          schema-generation:
            scripts:
#              create-target: create.sql
#              action: create
#              create-source: metadata
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:5432/catalog
    username: postgres
    password: GEpida820
    show-sql: true
    hibernate:
      ddl-auto: none
    open-in-view: false

  cache:
    infinispan:
        config: classpath:infinispan.xml

hu:
  webuni:
    tokenlib:
      keypaths:
        public: C:/Users/Kazimour Antal/public.pem

