server:
  port: 8054
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8050/eureka/

feign:
 user-ms:
  url: http://localhost:8060/api
  catalog-ms:
    url: http://localhost:8060/api

spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:5432/orders
    username: postgres
    password: GEpida820
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create

  artemis:
    broker-url: tcp://localhost:61616
  jms:
    pub-sub-domain: true

hu:
  webuni:
    tokenlib:
      keypaths:
        public: C:/Users/Kazimour Antal/public.pem
