server:
  port: 8052
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8050/eureka/

spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:5432/user
    username: postgres
    password: GEpida820
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create


hu:
  webuni:
    tokenlib:
      keypaths:
        private: C:/Users/Kazimour Antal/private.pem
        public: C:/Users/Kazimour Antal/public.pem